# permissions for end users to edit brokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: broker-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lindb-operator
    app.kubernetes.io/part-of: lindb-operator
    app.kubernetes.io/managed-by: kustomize
  name: broker-editor-role
rules:
- apiGroups:
  - lindb.lindb.io
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lindb.lindb.io
  resources:
  - brokers/status
  verbs:
  - get
