kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lindb-cluster-storage-disk
  labels:
    app-name: lindb-cluster-storage-disk
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi