apiVersion: lindb.lindb.io/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: cluster-sample
    app.kubernetes.io/part-of: lindb-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: lindb-operator
  name: cluster-sample
spec:
  paused: false
  etcdNamespace: /lindb-cluster
  etcdEndpoints:
    - http://etcd:2379
  image: wangguohao/lindb:v0.2.1
  brokers:
    replicas: 1
    httpPort: 9000
    grpcPort: 9001
    monitor:
      reportInterval: 10s
      url: http://broker1:9000/api/v1/write?db=_internal
    logging:
      dir: /lindb/broker1
      level: debug
  storages:
    replicas: 1
    grpcPort: 2891
    httpPort: 2892
    walDir: /lindb/storage1/wal
    tsdbDir: /lindb/storage1/data
    monitor:
      reportInterval: 10s
      url: http://broker1:9000/api/v1/write?db=_internal
    logging:
      dir: /lindb/storage1
      level: debug
