apiVersion: lindb.lindb.io/v1alpha1
kind: Cluster
metadata:
  labels:
    lindb.lindb.io/tenant: lindb-user1
  name: cluster-sample
spec:
  paused: false
  etcdNamespace: /lindb-cluster
  etcdEndpoints:
    - http://etcd:2379
  image: wangguohao/lindb:v0.2.1
  cloud:
    type: aws
    storage:
      type: shared
      storageClass: gp2
      storageSize: 10Gi
      mountPath: /data
  brokers:
    replicas: 1
    httpPort: 9000
    grpcPort: 9001
    monitor:
      reportInterval: 10s
      url: http://localhost:9000/api/v1/write?db=_internal
  storages:
    replicas: 1
    grpcPort: 2891
    httpPort: 2892
    monitor:
      reportInterval: 10s
      url: http://localhost:9000/api/v1/write?db=_internal