apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --controller deployment --volumes hostPath
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: broker1
  name: broker1
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: broker1
status:
  loadBalancer: {}
