apiVersion: v1
data:
  broker1.toml: |
    [coordinator]
    namespace = "/lindb-cluster"
    endpoints = ["http://etcd:2379"]

    [broker]
    [broker.http]
    port = 9000

    [broker.grpc]
    port = 9001

    [monitor]
    report-interval = "10s"
    url = "http://broker1:9000/api/v1/write?db=_internal"

    [logging]
    dir = "/lindb/broker1"
    level = "debug"
  storage1.toml: |+
    [coordinator]
    namespace = "/lindb-cluster"
    endpoints = ["http://etcd:2379"]

    [storage]
    indicator = 1

    [storage.grpc]
    port = 2891

    [storage.wal]
    dir = "/lindb/storage1/wal"

    [storage.tsdb]
    dir = "/lindb/storage1/data"

    [monitor]
    report-interval = "10s"
    url = "http://broker1:9000/api/v1/write?db=_internal"

    [logging]
    dir = "/lindb/storage1"
    level = "debug"
kind: ConfigMap
metadata:
  name: lindb-config
  namespace: default